---
- name: Create directory for SSL certificate
  file:
    path: "/etc/letsencrypt/live/{{ domain }}"
    state: directory
    mode: 0755
    owner: root
    group: root

# Ansible doesn't generate certificates if they already exist
- name: Generate SSL private key
  openssl_privatekey:
    path: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"
    size: 4096

- name: Generate SSL certificate signing request (CSR)
  openssl_csr:
    path: "/etc/letsencrypt/live/{{ domain }}/cert.csr"
    privatekey_path: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"
    common_name: "{{ domain }}"
    state: present

- name: Generate Self-Signed SSL certificate
  openssl_certificate:
    path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
    privatekey_path: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"
    csr_path: "/etc/letsencrypt/live/{{ domain }}/cert.csr"
    provider: selfsigned
    # 3650 => 10 years from now
    selfsigned_not_after: "{{ lookup('pipe', 'date -d ' ~ 3650 ~ 'days +%Y%m%d%H%M%SZ') }}"
    state: present

- name: Copy Let's Encrypt ssl options file
  copy:
    src: "options-ssl-nginx.conf"
    dest: "/etc/letsencrypt/options-ssl-nginx.conf"
    owner: root
    group: root
    mode: 0644

- name: Generate Diffie-Hellman parameters if not already present
  command: openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048
  args:
    creates: /etc/letsencrypt/ssl-dhparams.pem

- name: Ensure correct permissions for the dhparams file
  file:
    path: /etc/letsencrypt/ssl-dhparams.pem
    owner: root
    group: root
    mode: '0644'

