sudo_password: <sudo password for the ansible user>

# The user is "default"
redis_password: <password>

# Used for criptographic operations
registry_password: <password>

# User used by the correctomatic processes to access the registry
correctomatic_registry_user: <username>
correctomatic_registry_password: <password>

# List of users that can access the docker registry
docker_registry_users:
  - { username: "{{ correctomatic_registry_user }}", password: "{{ correctomatic_registry_password }}" }
  # Create more users as needed
  # - { username: user1, password: pass1 }
  # - { username: user2, password: pass2 }
  # - { username: user3, password: pass3 }
  # ...

# API secrets
api:
  # Database user
  db_user: "correctomatic"
  db_password: "correctomatic"

  # First root user for the api
  root_user: "root"
  root_password: "correctomatic"

  # JWT secret key
  jwt_secret_key: "correctomatic"

# Password for app database user
app_db_user: "correctomatic"
app_db_password: "correctomatic"
