---
- name: Include shared folder creation
  import_tasks: ../../common/tasks/shared_folder.yml

- name: Include correctomatic network creation
  import_tasks: ../../common/tasks/correctomatic_network.yml

- name: Setup API's database
  include_role:
    name: postgresql-database-setup
  vars:
    db_name: "{{ correctomatic.api.db.name }}"
    db_user: "{{ api.db_user }}"
    db_password: "{{ api.db_password }}"
    encoding: "{{ correctomatic.api.db.encoding }}"
    lc_collate: "{{ correctomatic.api.db.lc_collate }}"
    lc_ctype: "{{ correctomatic.api.db.lc_ctype }}"
    postgresql_version: "{{ postgresql.version }}"

- name: Correctomatic API container
  docker_container:
    name: correctomatic-api
    image: "{{ correctomatic.api.image }}:{{ correctomatic.api.tag }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ correctomatic.network.name }}"
    pull: yes
    env:
      PORT: "3000"
      DB_NAME: "{{ correctomatic.api.db.name }}"
      DB_USER: "{{ api.db_user }}"
      DB_PASSWORD: "{{ api.db_password }}"
      DB_HOST: postgres
      DB_PORT: "5432"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_USER: default
      REDIS_PASSWORD: "{{ redis_password }}"
      JWT_SECRET_KEY: "{{ api.jwt_secret_key }}"
      LOG_LEVEL: "{{ correctomatic.api.log_level }}"
      UPLOAD_DIRECTORY: "{{ correctomatic.shared_folder }}"
    volumes:
      # Exercises' folder
      - "{{ correctomatic.shared_folder }}:{{ correctomatic.shared_folder }}:rw"
    published_ports:
      - "{{ correctomatic.api.port }}:3000"
    # Redis is running on the VPS
    etc_hosts:
      redis: "{{ correctomatic.network.gateway }}"
      postgres: "{{ correctomatic.network.gateway }}"

- name: Run Sequelize migrations
  command: |
    docker exec correctomatic-api yarn migrate
  register: migration_result

- name: Output migration result
  debug:
    var: migration_result.stdout

- name: Create first root user
  command: |
    docker exec -e ROOT_USER="{{ api.root_user }}" -e ROOT_PASSWORD="{{ api.root_password }}" correctomatic-api yarn create-root-user
  register: root_user_result
