---
- name: Create the app directory
  file:
    path: /correctomatic/app
    state: directory
    mode: '0755'
    owner: root
    group: docker

- name: Create the configuration directory
  file:
    path: /correctomatic/app/config
    state: directory
    mode: '0755'
    owner: root
    group: docker

- name: Create the uploads directory
  file:
    path: "{{ correctomatic.app.uploads_dir }}"
    state: directory
    mode: '0777'
    owner: root
    group: docker

- name: Generate a private key
  community.crypto.openssl_privatekey:
    path: /correctomatic/app/config/private.key
    type: RSA
    size: 2048

- name: Generate a public key from the private key
  openssl_publickey:
    path: /correctomatic/app/config/public.key
    privatekey_path: /correctomatic/app/config/private.key

- name: Change permissions of the private key file to be readable by all
  file:
    path: /correctomatic/app/config/private.key
    mode: '0644'
